### ISSUE TITLE
build error on windows

### ISSUE THREAD

**Issue by BruceChen2017** [chrisvest/xv#14]
On windows 10, I run `cargo install xv`, but I get  such error: `error: failed to run custom build command for ncurses v5.99.0`

**Comment by chrisvest** [comment]
Yeah, Cursive does not have any build instructions for Windows: https://github.com/gyscos/Cursive/wiki/Install-ncurses

If you switch to make it use the `pancurses` backend, then in theory it should work on Windows: https://github.com/gyscos/Cursive/wiki/Backends

I haven't (and can't) tried this, though.

The crossterm backend most likely does not work, because it is at least broken on Linux.

Please update the wiki with instructions if you figure out how to do this.

**Comment by chrisvest** [comment]
Quick ping to @gyscos in case he has any insights.

**Comment by chrisvest** [comment]
@BruceChen2017 something you can try:

* Make sure you have what you need for running with pancurses: https://github.com/gyscos/Cursive/wiki/Backends
* Get the XV sources from git.
* In the checkout directory, install with `cargo install  --no-default-features --features pancurses-backend`.

**Comment by BruceChen2017** [comment]
@chrisvest Yes,it works with last step `cargo install --path .  --no-default-features --features pancurses-backend`
